use xladd_derive::xl_func;
use xladd::Reg;
use log::*;

#[xl_func()]
fn add(arg1: f64, arg2: f64) -> Result<f64, Box<dyn std::error::Error>> {
    Ok(arg1 + arg2)
}

#[no_mangle]
pub extern "stdcall" fn xlAutoOpen() -> i32 {
    let reg = Reg::new();
    register_add(&reg); // register_add is generated by the xl_func macro
    1 // Must return 1 to signal to excel SUCCESS
}
